name: openssl_assets_workspace
description: Pub workspace for the openssl_assets package and its examples.
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - packages/openssl_assets
  - tool

dev_dependencies:
  lints: ^6.0.0
