// GENERATED by tool/bin/write_manifest.dart. Do not edit by hand.
//
// Hashes of the prebuilt libraries attached to the GitHub release named by
// [releaseTag]. The hook refuses to use any file whose sha256 is not listed
// here (ADR-0007). A `null` [releaseTag] means no release exists yet; only
// `local_path`, `local_build`, `system` or `test_directory` can work then.

// dart format off

import 'hook/manifest_model.dart';

const String releaseTag = 'v3.5.8-1';

const Manifest compiledInManifest = Manifest(
  releaseTag: releaseTag,
  opensslVersion: '3.5.8',
  opensslCommit: 'f4dc4d58b48d346a8270183f89acf826d459b0ca',
  sourceTarballSha256: 'a8f84a39918ec6415ce765d9b429d313ba97b8143169c172e734b9514464f5b2',
  assets: {
    'libopenssl3_crypto.arm.android.so': AssetInfo(
      file: 'libopenssl3_crypto.arm.android.so',
      sha256: 'a078c98ecf4d4ed9eba473abe331e9e7ce538d58a5a9a2e21c3c3eddc38b79df',
      size: 4797708,
      target: 'android-arm',
    ),
    'libopenssl3_crypto.arm64.android.so': AssetInfo(
      file: 'libopenssl3_crypto.arm64.android.so',
      sha256: '955a16e99e823deeb25c2b13b8172a0b1c6dcc5c4a80e596b8f0c63c0634c089',
      size: 6494976,
      target: 'android-arm64',
    ),
    'libopenssl3_crypto.arm64.ios.dylib': AssetInfo(
      file: 'libopenssl3_crypto.arm64.ios.dylib',
      sha256: 'fd66d163137095ee4e08dba78e197114572bdb339db0f51b2968b9635d5b5540',
      size: 4858768,
      target: 'ios-arm64',
    ),
    'libopenssl3_crypto.arm64.ios_sim.dylib': AssetInfo(
      file: 'libopenssl3_crypto.arm64.ios_sim.dylib',
      sha256: '8f9e7b2686d62ad69c4b8c7f7cf723a31ef66c22c7b9e596bb633f0e1772d185',
      size: 4858656,
      target: 'ios_sim-arm64',
    ),
    'libopenssl3_crypto.arm64.linux.so': AssetInfo(
      file: 'libopenssl3_crypto.arm64.linux.so',
      sha256: '429e6d0d5f7e7bfe3a1f834d92805d428b03bb6079f6c0c91864b787d83a0216',
      size: 6806824,
      target: 'linux-arm64',
    ),
    'libopenssl3_crypto.arm64.linux_musl.so': AssetInfo(
      file: 'libopenssl3_crypto.arm64.linux_musl.so',
      sha256: 'f344e456b5257f3925eee9c76e6c6291b9e81d44defd1e7fd9d28576d7c3235f',
      size: 6804776,
      target: 'linux_musl-arm64',
    ),
    'libopenssl3_crypto.arm64.macos.dylib': AssetInfo(
      file: 'libopenssl3_crypto.arm64.macos.dylib',
      sha256: '6205f297790b10e700b16be5cc9016f2d7736e74e675f6836bca5191a2e0d16a',
      size: 4859376,
      target: 'macos-arm64',
    ),
    'libopenssl3_crypto.riscv64.linux.so': AssetInfo(
      file: 'libopenssl3_crypto.riscv64.linux.so',
      sha256: 'a87af5a83147a400294852d8f655e664e50bd1e49d4c5fa056865859f93b9738',
      size: 5476880,
      target: 'linux-riscv64',
    ),
    'libopenssl3_crypto.x64.android.so': AssetInfo(
      file: 'libopenssl3_crypto.x64.android.so',
      sha256: '92fa29a49c9cfc21b886ed63dd3601d6903d871cfe1137b9baeedf96784e008e',
      size: 6753696,
      target: 'android-x64',
    ),
    'libopenssl3_crypto.x64.ios_sim.dylib': AssetInfo(
      file: 'libopenssl3_crypto.x64.ios_sim.dylib',
      sha256: '037c2473a2db844872249e03a28eef4d3f78c570f47447d3642000c2fb0dc58f',
      size: 5375872,
      target: 'ios_sim-x64',
    ),
    'libopenssl3_crypto.x64.linux.so': AssetInfo(
      file: 'libopenssl3_crypto.x64.linux.so',
      sha256: 'ac567cdebf4f8f61ee59a1013d6b5bb637905036be05f24ebf0108aa114760b4',
      size: 7154928,
      target: 'linux-x64',
    ),
    'libopenssl3_crypto.x64.linux_musl.so': AssetInfo(
      file: 'libopenssl3_crypto.x64.linux_musl.so',
      sha256: 'a687665770862947f86123007de1050a53535d1bf509687807a738f2cc47ceb1',
      size: 7252392,
      target: 'linux_musl-x64',
    ),
    'libopenssl3_crypto.x64.macos.dylib': AssetInfo(
      file: 'libopenssl3_crypto.x64.macos.dylib',
      sha256: '6d27072daea2563270919adae0903d835818cd6d6168f239f04d9b29a5d37162',
      size: 5368592,
      target: 'macos-x64',
    ),
    'openssl3_crypto.arm64.windows.dll': AssetInfo(
      file: 'openssl3_crypto.arm64.windows.dll',
      sha256: 'e33c5001178f77401927612f008e17849f1fd760f517b084afd403638a143207',
      size: 3985920,
      target: 'windows-arm64',
    ),
    'openssl3_crypto.x64.windows.dll': AssetInfo(
      file: 'openssl3_crypto.x64.windows.dll',
      sha256: 'd2810e4d0d7b7eb55c88d631e718a82890a939e927bc6311f144531240f905e0',
      size: 5437952,
      target: 'windows-x64',
    ),
  },
);
