// GENERATED by tool/bin/write_manifest.dart. Do not edit by hand.
//
// Hashes of the prebuilt libraries attached to the GitHub release named by
// [releaseTag]. The hook refuses to use any file whose sha256 is not listed
// here (ADR-0007). A `null` [releaseTag] means no release exists yet; only
// `local_path`, `local_build`, `system` or `test_directory` can work then.

// dart format off

import 'hook/manifest_model.dart';

const String? releaseTag = null;

const Manifest compiledInManifest = Manifest(
  releaseTag: releaseTag,
  opensslVersion: '3.5.8',
  opensslCommit: 'f4dc4d58b48d346a8270183f89acf826d459b0ca',
  sourceTarballSha256: null,
  assets: {},
);
