// GENERATED by tool/bin/write_manifest.dart. Do not edit by hand.
//
// Hashes of the prebuilt libraries attached to the GitHub release named by
// [releaseTag]. The hook refuses to use any file whose sha256 is not listed
// here (ADR-0007). A `null` [releaseTag] means no release exists yet; only
// `local_path`, `local_build`, `system` or `test_directory` can work then.

// dart format off

import 'hook/manifest_model.dart';

const String releaseTag = 'v3.5.8-2';

const Manifest compiledInManifest = Manifest(
  releaseTag: releaseTag,
  opensslVersion: '3.5.8',
  opensslCommit: 'f4dc4d58b48d346a8270183f89acf826d459b0ca',
  sourceTarballSha256: 'a8f84a39918ec6415ce765d9b429d313ba97b8143169c172e734b9514464f5b2',
  assets: {
    'libopenssl3_crypto.arm.android.so': AssetInfo(
      file: 'libopenssl3_crypto.arm.android.so',
      sha256: '60032f002a202675ba3f1aa36ebeb0c3d23e4cbc490a0f215ea64dae9af63771',
      size: 4797708,
      target: 'android-arm',
    ),
    'libopenssl3_crypto.arm.linux.so': AssetInfo(
      file: 'libopenssl3_crypto.arm.linux.so',
      sha256: '7698de60de047762423d60debe2936a10ffe793dcbf16156d8be858183ebc582',
      size: 4051832,
      target: 'linux-arm',
    ),
    'libopenssl3_crypto.arm64.android.so': AssetInfo(
      file: 'libopenssl3_crypto.arm64.android.so',
      sha256: '147b93df12a32c00f0008504ab351057707418c2fa7c08e2e477706c48618dab',
      size: 6494976,
      target: 'android-arm64',
    ),
    'libopenssl3_crypto.arm64.ios.dylib': AssetInfo(
      file: 'libopenssl3_crypto.arm64.ios.dylib',
      sha256: 'bb31945fab3ac246b08d23a16a9c4a51ecc3c3379ae8299d1afc193912a4a8e8',
      size: 4858768,
      target: 'ios-arm64',
    ),
    'libopenssl3_crypto.arm64.ios_sim.dylib': AssetInfo(
      file: 'libopenssl3_crypto.arm64.ios_sim.dylib',
      sha256: '27bee470bb4378cc8c943c182979a833bcc4c9dfe78d82c6309a6c60731eb0bb',
      size: 4858656,
      target: 'ios_sim-arm64',
    ),
    'libopenssl3_crypto.arm64.linux.so': AssetInfo(
      file: 'libopenssl3_crypto.arm64.linux.so',
      sha256: '38cb9f5c0300b36fcef4195cd973a0ba827d721f33a6b8ebdbb545f269003375',
      size: 6806824,
      target: 'linux-arm64',
    ),
    'libopenssl3_crypto.arm64.linux_musl.so': AssetInfo(
      file: 'libopenssl3_crypto.arm64.linux_musl.so',
      sha256: '395f41726a5545c09fa12f99117baa69ae4ad3adb1511590f6c350c057b65dae',
      size: 6804776,
      target: 'linux_musl-arm64',
    ),
    'libopenssl3_crypto.arm64.macos.dylib': AssetInfo(
      file: 'libopenssl3_crypto.arm64.macos.dylib',
      sha256: '88ef0e8ecc49a09627fff67b1fee54787490569dfae3bdc78a3c79bd702bea27',
      size: 4859376,
      target: 'macos-arm64',
    ),
    'libopenssl3_crypto.riscv64.linux.so': AssetInfo(
      file: 'libopenssl3_crypto.riscv64.linux.so',
      sha256: '317aac0b8895c89d7d4fdbc6a5f0b7e5b128c811aa375f26028bd5e7ed58ec10',
      size: 5476880,
      target: 'linux-riscv64',
    ),
    'libopenssl3_crypto.x64.android.so': AssetInfo(
      file: 'libopenssl3_crypto.x64.android.so',
      sha256: '1a20243a8daf1ab2b866efdc3bdd6c834487020a05ed009a4aa36ec4532269f9',
      size: 6753696,
      target: 'android-x64',
    ),
    'libopenssl3_crypto.x64.ios_sim.dylib': AssetInfo(
      file: 'libopenssl3_crypto.x64.ios_sim.dylib',
      sha256: '8b0379385105c9d3da2f1af103bfdb225788ddde61f90e9609fc39292d2320f2',
      size: 5375872,
      target: 'ios_sim-x64',
    ),
    'libopenssl3_crypto.x64.linux.so': AssetInfo(
      file: 'libopenssl3_crypto.x64.linux.so',
      sha256: '5b233ad21e00d70c6d19572cc6b9e4a4ed981fb12c7568238afabe04c3476da3',
      size: 7154928,
      target: 'linux-x64',
    ),
    'libopenssl3_crypto.x64.linux_musl.so': AssetInfo(
      file: 'libopenssl3_crypto.x64.linux_musl.so',
      sha256: '2fa034c50f3ad9e2cb54b92c2ea58efc68d0cd8459055760e5bd776bfcca7a7a',
      size: 7252392,
      target: 'linux_musl-x64',
    ),
    'libopenssl3_crypto.x64.macos.dylib': AssetInfo(
      file: 'libopenssl3_crypto.x64.macos.dylib',
      sha256: '6d993b1003c6d25673bf6875bbd4357911d65b40db4eab3da1f546495fe2b0c3',
      size: 5368592,
      target: 'macos-x64',
    ),
    'openssl3_crypto.arm64.windows.dll': AssetInfo(
      file: 'openssl3_crypto.arm64.windows.dll',
      sha256: '11c1cdec3b4477dea35ffb5efb1ff96f570db568e254de0f78f24d30b42d3d7b',
      size: 3985920,
      target: 'windows-arm64',
    ),
    'openssl3_crypto.x64.windows.dll': AssetInfo(
      file: 'openssl3_crypto.x64.windows.dll',
      sha256: 'c6c049d7a8ba5e9b9eb8d6fb95a2506b5e1d2a918371ae6c97888a3c3097412c',
      size: 5437952,
      target: 'windows-x64',
    ),
  },
);
