/// The release manifest: which prebuilt files exist for a release and their
/// sha256 digests. The compiled-in copy lives in `../manifest.dart`
/// (generated by `tool/bin/write_manifest.dart`); the same structure is
/// published as `manifest.json` on the GitHub release.
library;

import 'dart:convert';

final class AssetInfo {
  /// Release file name, e.g. `libopenssl3_crypto.arm64.macos.dylib`.
  final String file;

  /// Lower-case hex sha256 of the file.
  final String sha256;
  final int size;

  /// Target id, e.g. `macos-arm64`.
  final String target;

  const AssetInfo({
    required this.file,
    required this.sha256,
    required this.size,
    required this.target,
  });

  factory AssetInfo.fromJson(String file, Map<String, Object?> json) =>
      AssetInfo(
        file: file,
        sha256: json['sha256'] as String,
        size: json['size'] as int,
        target: json['target'] as String,
      );

  Map<String, Object?> toJson() => {
    'target': target,
    'sha256': sha256,
    'size': size,
  };
}

final class Manifest {
  /// Git tag of the release these assets are attached to (`v0.1.0`), or
  /// `null` when no release exists yet (development checkouts).
  final String? releaseTag;
  final String opensslVersion;
  final String? opensslCommit;

  /// Sha256 of the upstream `openssl-<version>.tar.gz`, used by
  /// `local_build` to verify the source it downloads. `null` until recorded.
  final String? sourceTarballSha256;

  /// Keyed by release file name.
  final Map<String, AssetInfo> assets;

  const Manifest({
    required this.releaseTag,
    required this.opensslVersion,
    required this.opensslCommit,
    required this.sourceTarballSha256,
    required this.assets,
  });

  factory Manifest.fromJson(Map<String, Object?> json) => Manifest(
    releaseTag: json['release_tag'] as String?,
    opensslVersion: json['openssl_version'] as String,
    opensslCommit: json['openssl_commit'] as String?,
    sourceTarballSha256: json['source_tarball_sha256'] as String?,
    assets: {
      for (final MapEntry(:key, :value)
          in (json['assets'] as Map<String, Object?>).entries)
        key: AssetInfo.fromJson(key, value as Map<String, Object?>),
    },
  );

  factory Manifest.parse(String jsonText) =>
      Manifest.fromJson(jsonDecode(jsonText) as Map<String, Object?>);

  Map<String, Object?> toJson() => {
    'release_tag': releaseTag,
    'openssl_version': opensslVersion,
    'openssl_commit': opensslCommit,
    'source_tarball_sha256': sourceTarballSha256,
    'assets': {
      for (final name in assets.keys.toList()..sort())
        name: assets[name]!.toJson(),
    },
  };

  AssetInfo? operator [](String file) => assets[file];
}
